//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckersWebsite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckersWebsite.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        public static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Checkers.
        /// </summary>
        public static string AmericanCheckers {
            get {
                return ResourceManager.GetString("AmericanCheckers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Checkers Optional Jump.
        /// </summary>
        public static string AmericanCheckersOptionalJump {
            get {
                return ResourceManager.GetString("AmericanCheckersOptionalJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Won.
        /// </summary>
        public static string BlackWin {
            get {
                return ResourceManager.GetString("BlackWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level 1.
        /// </summary>
        public static string Computer1 {
            get {
                return ResourceManager.GetString("Computer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level 2.
        /// </summary>
        public static string Computer2 {
            get {
                return ResourceManager.GetString("Computer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level 3.
        /// </summary>
        public static string Computer3 {
            get {
                return ResourceManager.GetString("Computer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level 4.
        /// </summary>
        public static string Computer4 {
            get {
                return ResourceManager.GetString("Computer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level 5.
        /// </summary>
        public static string Computer5 {
            get {
                return ResourceManager.GetString("Computer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level 6.
        /// </summary>
        public static string Computer6 {
            get {
                return ResourceManager.GetString("Computer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level 7.
        /// </summary>
        public static string Computer7 {
            get {
                return ResourceManager.GetString("Computer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level 8.
        /// </summary>
        public static string Computer8 {
            get {
                return ResourceManager.GetString("Computer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Level 9.
        /// </summary>
        public static string Computer9 {
            get {
                return ResourceManager.GetString("Computer9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawn.
        /// </summary>
        public static string Drawn {
            get {
                return ResourceManager.GetString("Drawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Position.
        /// </summary>
        public static string FromPosition {
            get {
                return ResourceManager.GetString("FromPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone else already joined this game.
        /// </summary>
        public static string GameJoined {
            get {
                return ResourceManager.GetString("GameJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        public static string Human {
            get {
                return ResourceManager.GetString("Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastic.
        /// </summary>
        public static string Plastic {
            get {
                return ResourceManager.GetString("Plastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Checkers.
        /// </summary>
        public static string PoolCheckers {
            get {
                return ResourceManager.GetString("PoolCheckers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Won.
        /// </summary>
        public static string WhiteWin {
            get {
                return ResourceManager.GetString("WhiteWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
    }
}
